#公用配置
DEBUG = True
SQLALCHEMY_ECHO = False
SQLALCHEMY_TRACK_MODIFICATIONS = False
SQLALCHEMY_ENCODING = "utf8mb4"
SECRET_KEY = "base"
DEBUG_TB_INTERCEPT_REDIRECTS = False
AUTH_COOKIE_NAME = "cookiename"